version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cce-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16chvhk566n38"
s3_prefix = "cce-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
